# Notebook 1

Pada notebook ini, disajikan materi terkait metode untuk mengatasi data yang hilang secara umum (NaN) menggunakan bahasa pemrograman Python dan library Pandas.

Secara umum, data yang hilang dapat berbentuk berbagai macam jenisnya. Dapat berupa NaN, string kosong (''), atau bahkan dalam bentuk string ('null', 'kosong', 'hilang'). Namun, pada notebook ini akan disajikan cara menangani data yang hilang secara umum saja, yaitu dengan langsung menghilangkan baris yang terdapat data hilangnya. Berikut demonstrasi kodenya beserta dengan penjelasan dengan komentar.

In [1]:
# Impor library yang diperlukan
import numpy as np
import pandas as pd

# Untuk sekarang, data yang digunakan hanyalah data dummy
df = pd.DataFrame({
    'A': [10, 20, np.nan, np.nan, 30, np.nan, 40, 50, 60, np.nan],
    'B': [np.nan, 2, 4, 6, 8, np.nan, np.nan, 10, 12, 14]
})

In [2]:
# Menampilkan data
df

      A     B
0  10.0   NaN
1  20.0   2.0
2   NaN   4.0
3   NaN   6.0
4  30.0   8.0
5   NaN   NaN
6  40.0   NaN
7  50.0  10.0
8  60.0  12.0
9   NaN  14.0

Seperti yang sudah dijelaskan sebelumnya, pada notebook ini, metode yang akan digunakan untuk menangani data yang hilang adalah dengan langsung menghapusnya, dengan fitur bawaan Pandas, yaitu dengan method ```dropna()```.

In [3]:
# Menghapus data yang terindikasi sebagai null
df = df.dropna()

In [4]:
# Menampilkan data yang sudah dibersihkan
df

      A     B
1  20.0   2.0
4  30.0   8.0
7  50.0  10.0
8  60.0  12.0

Dengan kode berikut, kita telah berhasil menangani data yang hilang. Namun, perlu diketahui bahwa metode ini memiliki beberapa kelemahan, yaitu cenderung menghilangkan data yang penting dan mengurangi jumlah baris data secara signifikan. Sehingga, untuk ke depannya jika ingin membangun model machine learning, maka model yang akan dibangun akan kesulitan untuk menangkap pola dari data yang ada karena kurangnya jumlah data akibat telah dihapus.

Pada notebook selanjutnya, akan dibahas metode lain, yaitu metode imputasi atau mengganti data yang hilang dengan nilai rerata, median, dan modus dari kolom yang ditangani.